#!/usr/bin/env node
/**
 * The harness CLI.
 *
 *   node tools/sim/run.js                                  measure the live baseline
 *   node tools/sim/run.js --sweep curve.cap_multiplier=2.5,3.0,3.5
 *   node tools/sim/run.js --stake 1000 --rounds 100
 *   node tools/sim/run.js --out docs/tuning-report.md      write the report
 *
 * Output is a markdown table, because the deliverable is "the harness and its
 * output" and the output has to be readable by someone who is not going to run
 * it. `--json` additionally writes the raw numbers for anything that wants to
 * chart them.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const { loadFromFile, loadFromSeed, withOverride } = require('./config');
const { runHarness } = require('./harness');
const chickenPlayers = require('./player');
const popPlayers = require('./popShotPlayer');

/** Which synthetic population belongs to which game. */
const PLAYERS = {
  chicken_run: { population: chickenPlayers.POPULATION, play: chickenPlayers.playRound },
  pop_shot: { population: popPlayers.POPULATION, play: popPlayers.playRound },
};

function parseArgs(argv) {
  const args = {
    config: 'baseline-v0',
    game: 'chicken_run',
    file: null,
    compare: null,
    sweep: null,
    stake: 300,
    rounds: 60,
    players: 200,
    bankroll: 6000,
    seed: 20260101,
    out: null,
    json: null,
  };

  for (let i = 0; i < argv.length; i++) {
    const key = argv[i];
    const value = argv[i + 1];
    switch (key) {
      case '--config': args.config = value; i++; break;
      case '--game': args.game = value; i++; break;
      case '--file': args.file = value; i++; break;
      case '--compare': args.compare = value; i++; break;
      case '--sweep': args.sweep = value; i++; break;
      case '--stake': args.stake = Number(value); i++; break;
      case '--rounds': args.rounds = Number(value); i++; break;
      case '--players': args.players = Number(value); i++; break;
      case '--bankroll': args.bankroll = Number(value); i++; break;
      case '--seed': args.seed = Number(value); i++; break;
      case '--out': args.out = value; i++; break;
      case '--json': args.json = value; i++; break;
      case '--help':
        console.log(fs.readFileSync(__filename, 'utf8').split('*/')[0]);
        process.exit(0);
        break;
      default:
        if (key.startsWith('--')) throw new Error(`unknown option ${key}`);
    }
  }
  return args;
}

const pct = (x) => `${(x * 100).toFixed(1)}%`;
const money = (c) => `$${(c / 100).toFixed(2)}`;

/** One variant's table of archetypes. */
function archetypeTable(result) {
  const header =
    '| archetype | policy | mean reach | mean target | RTP | win rate | any payout | died | busted | median rounds |\n' +
    '|---|---|---|---|---|---|---|---|---|---|\n';

  const rows = Object.entries(result.byArchetype).map(([name, s]) =>
    `| ${name} | ${s.policy} | ${s.meanReach.toFixed(1)} | ${s.meanTarget.toFixed(1)} | ` +
    `${pct(s.rtp)} | ${pct(s.winRate)} | ${pct(s.nonZeroRate)} | ${pct(s.deathRate)} | ` +
    `${pct(s.bustRate)} | ${s.medianRoundsSurvived} |`
  );

  return header + rows.join('\n') + '\n';
}

function report(args, variants) {
  const lines = [];
  lines.push('# Blitz tuning report');
  lines.push('');
  lines.push('Generated by `node tools/sim/run.js`. Every number here is reproducible:');
  lines.push('the harness threads one seeded PRNG and calls the same engine the server');
  lines.push('does — `buildQuote`, `materialiseCurve`, `multiplierBpForScore`, `payoutCents`,');
  lines.push('`advanceProfile`. Nothing is reimplemented, so these are measurements of the');
  lines.push('shipping economics rather than of a model of them.');
  lines.push('');
  lines.push('## Settings');
  lines.push('');
  lines.push(`- entry: **${money(args.stake)}** · starting bankroll **${money(args.bankroll)}**`);
  lines.push(`- ${args.players} synthetic players per archetype, up to ${args.rounds} rounds each`);
  lines.push(`- seed \`${args.seed}\`  ·  game **${args.game}**`);
  lines.push('');
  lines.push('The target engine adapts inside every career, so what is measured is the');
  lines.push('closed loop — player, engine, curve — not a fixed paytable.');
  lines.push('');

  lines.push('## Headline');
  lines.push('');
  lines.push('| variant | RTP (weighted) | win rate | any payout | bust rate | median rounds |');
  lines.push('|---|---|---|---|---|---|');
  for (const v of variants) {
    const o = v.result.overall;
    lines.push(
      `| ${v.label} | **${pct(o.weightedRtp)}** | ${pct(o.weightedWinRate)} | ` +
      `${pct(o.nonZeroRate)} | ${pct(o.bustRate)} | ${o.medianRoundsSurvived} |`
    );
  }
  lines.push('');
  lines.push('RTP is weighted by the population mix rather than pooled, so a rare archetype');
  lines.push('that survives many rounds cannot dominate a headline it does not represent.');
  lines.push('');

  for (const v of variants) {
    lines.push(`## ${v.label}`);
    lines.push('');
    lines.push(archetypeTable(v.result));
  }

  return lines.join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const base = args.file ? loadFromFile(args.file) : loadFromSeed(args.config);

  const variants = [];

  const players = PLAYERS[args.game];
  if (!players) throw new Error(`unknown --game '${args.game}'`);

  const measure = (params) =>
    runHarness({
      params,
      population: players.population,
      play: players.play,
      playersPer: args.players,
      rounds: args.rounds,
      stakeCents: args.stake,
      bankrollCents: args.bankroll,
      // The SAME seed for every variant, so a difference in the numbers is a
      // difference in the config and not in the dice.
      seed: args.seed,
    });

  if (args.compare) {
    // Candidate configs measured side by side against the same population.
    for (const spec of args.compare.split(',')) {
      const isFile = spec.endsWith('.json');
      variants.push({
        label: isFile ? path.basename(spec, '.json') : spec,
        result: measure(isFile ? loadFromFile(spec) : loadFromSeed(spec)),
      });
    }
  } else if (args.sweep) {
    const [dottedPath, listRaw] = args.sweep.split('=');
    if (!listRaw) throw new Error('--sweep expects path=v1,v2,v3');

    for (const raw of listRaw.split(',')) {
      const value = Number(raw);
      if (!Number.isFinite(value)) throw new Error(`sweep value '${raw}' is not a number`);
      variants.push({
        label: `${dottedPath} = ${raw}`,
        result: measure(withOverride(base, dottedPath, value)),
      });
    }
  } else {
    variants.push({
      label: args.file ? path.basename(args.file) : args.config,
      result: measure(base),
    });
  }

  const markdown = report(args, variants);

  if (args.out) {
    fs.mkdirSync(path.dirname(args.out), { recursive: true });
    fs.writeFileSync(args.out, markdown);
    console.log(`wrote ${args.out}`);
  } else {
    console.log(markdown);
  }

  if (args.json) {
    fs.mkdirSync(path.dirname(args.json), { recursive: true });
    fs.writeFileSync(args.json, JSON.stringify({ settings: args, variants }, null, 2));
    console.log(`wrote ${args.json}`);
  }
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error(`harness failed: ${err.message}`);
    process.exit(1);
  }
}

module.exports = { parseArgs, report };
