using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using SkillApp.ChickenRun.Audio;

namespace SkillApp.EditorTools
{
    /// <summary>
    /// Render every synthesised clip to a .wav and report its statistics.
    ///
    /// ── Why this exists ──────────────────────────────────────────────────────
    ///
    /// The sounds are generated by code (see ProceduralAudio), which means the
    /// usual way of checking them — open the asset and listen — does not apply.
    /// Worse, the failure modes are quiet ones: an envelope with the wrong sign
    /// produces silence, a gain that is too high produces a clipped buzz, and both
    /// look completely fine in the source.
    ///
    /// So this measures what was actually generated: peak, RMS, DC offset and
    /// duration. A clip that is silent, clipped or off-centre fails here rather
    /// than on a phone.
    ///
    /// It also writes the wavs out, so a human can listen to the whole set without
    /// building and installing an APK. The exported files are NOT used by the game
    /// and are not committed — the game synthesises its own at load.
    ///
    ///   Unity -batchmode -quit -executeMethod SkillApp.EditorTools.AudioPreview.Export
    /// </summary>
    public static class AudioPreview
    {
        private const string OutDir = "Build/AudioPreview";

        [MenuItem("SkillApp/Export Audio Preview")]
        public static void Export()
        {
            Directory.CreateDirectory(OutDir);

            var clips = new (string name, AudioClip clip)[]
            {
                ("hop", ProceduralAudio.Hop()),
                ("blocked", ProceduralAudio.Blocked()),
                ("thud", ProceduralAudio.Thud()),
                ("horn", ProceduralAudio.Horn()),
                ("splash", ProceduralAudio.Splash()),
                ("idle_pulse", ProceduralAudio.IdlePulse()),
                ("cash_charge", ProceduralAudio.CashCharge(0.7f)),
                ("cash_confirm", ProceduralAudio.CashConfirm()),
            };

            int failures = 0;
            var report = new StringBuilder();
            report.AppendLine("clip           ms     peak    rms     dc");

            foreach (var (name, clip) in clips)
            {
                var samples = new float[clip.samples];
                clip.GetData(samples, 0);

                float peak = 0f, sumSq = 0f, sum = 0f;
                foreach (float s in samples)
                {
                    float a = Mathf.Abs(s);
                    if (a > peak) peak = a;
                    sumSq += s * s;
                    sum += s;
                }

                float rms = Mathf.Sqrt(sumSq / Mathf.Max(1, samples.Length));
                float dc = sum / Mathf.Max(1, samples.Length);
                int ms = Mathf.RoundToInt(clip.length * 1000f);

                report.AppendLine($"{name,-14} {ms,4}   {peak:F3}   {rms:F3}   {dc:F4}");

                // Audible, not clipped, and roughly centred. These are the three
                // ways a generated clip goes wrong without looking wrong.
                if (peak < 0.05f) { Fail(name, $"silent (peak {peak:F3})"); failures++; }
                if (peak > 0.999f) { Fail(name, $"clipped (peak {peak:F3})"); failures++; }
                if (rms < 0.005f) { Fail(name, $"near-silent (rms {rms:F4})"); failures++; }
                if (Mathf.Abs(dc) > 0.05f) { Fail(name, $"DC offset {dc:F4}"); failures++; }

                WriteWav(Path.Combine(OutDir, name + ".wav"), samples, clip.frequency);
            }

            Debug.Log($"[audio]\n{report}");
            Debug.Log($"[audio] wrote {clips.Length} wav files to {OutDir}");

            if (failures > 0)
            {
                // Throwing rather than EditorApplication.Exit: under -quit an Exit
                // call does not reliably propagate, and a build step that reports
                // success while producing silence is worse than no check.
                throw new BuildFailedException($"[audio] {failures} clip check(s) failed");
            }
        }

        private static void Fail(string name, string why) =>
            Debug.LogError($"[audio] {name}: {why}");

        /// <summary>Minimal 16-bit PCM mono WAV writer. Preview only.</summary>
        private static void WriteWav(string path, float[] samples, int sampleRate)
        {
            using var stream = new FileStream(path, FileMode.Create);
            using var w = new BinaryWriter(stream);

            int dataBytes = samples.Length * 2;

            w.Write(Encoding.ASCII.GetBytes("RIFF"));
            w.Write(36 + dataBytes);
            w.Write(Encoding.ASCII.GetBytes("WAVE"));
            w.Write(Encoding.ASCII.GetBytes("fmt "));
            w.Write(16);                       // PCM header size
            w.Write((short)1);                 // format: PCM
            w.Write((short)1);                 // channels: mono
            w.Write(sampleRate);
            w.Write(sampleRate * 2);           // byte rate
            w.Write((short)2);                 // block align
            w.Write((short)16);                // bits per sample
            w.Write(Encoding.ASCII.GetBytes("data"));
            w.Write(dataBytes);

            foreach (float s in samples)
            {
                w.Write((short)(Mathf.Clamp(s, -1f, 1f) * short.MaxValue));
            }
        }
    }
}
